# name of the software
name: MATH 2310

project:
  version: 1.0.0
  download_url: "{{ site.baseurl }}/Syllabus.pdf"
  download_text: Syllabus

license:
  software: 
  software_url:

  docs: Collab
  docs_url:

links:
  header:
    - title: 
      icon: 
      brand: false
      url:
  homepage:
    - title:
      icon:
      brand: false
      url:
  footer:
    - title:
      icon: 
      brand: true
      url: 
    - title:
      icon:
      url:

ui:
  mode: 'light' # 'auto', 'dark', 'light'
  brand:
    dark: "#00ceff"
    light: "#a20000"
  border_color:
    dark: "#5f5f5f"
    light: "#dee2e6"
  header:
    trianglify: true
    dark:
      color1: "#062a48"
      color2: "#304e67"
    light:
      color1: "#080331"
      color2: "#673051"
  masthead:
    color:
      dark: "#fff"
      light: "#fff"
    align:
      homepage: 'center'
      page: 'left'

social:
  github:
    user: allejo
    repo: jekyll-docs-theme
  twitter:
    enabled: false
    via:
    hash:
    account:
  facebook:
    enabled: false
    profileUrl:

analytics:
  google: UA-123456-1

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - jekyll-docs-theme.gemspec
  - LICENSE.md
  - README.md
  - screenshot.png
